import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {buildGoldenArtifacts} from '../scripts/build-gsat-115-chinese-golden.mjs';

const {raw,staging}=buildGoldenArtifacts();
assert.equal(raw.questions.length,36);
assert.equal(raw.questions.reduce((sum,q)=>sum+q.points,0),100);
assert.deepEqual(raw.questions.map(q=>q.question_number),Array.from({length:36},(_,i)=>i+1));
assert.equal(new Set(raw.questions.map(q=>q.id)).size,36);
assert.equal(raw.questions.every(q=>q.answer_match&&q.stem&&q.source_url.includes('ceec.edu.tw')),true);
assert.equal(raw.questions.filter(q=>q.questionType==='single_choice').length,26);
assert.equal(raw.questions.filter(q=>q.questionType==='multiple_choice').length,7);
assert.equal(raw.questions.filter(q=>q.questionType==='short_answer').length,3);
assert.equal(raw.groups.length,9);
assert.equal(raw.groups.filter(g=>g.rights_status==='metadata_only_pending_rights').length,7);
assert.equal(raw.questions.filter(q=>q.group_id).length,26);
assert.equal(raw.questions.filter(q=>[32,33,34].includes(q.question_number)).every(q=>q.grading_rubric?.url.includes('ceec.edu.tw')),true);
assert.equal(JSON.stringify(raw.questions.find(q=>q.question_number===25).answer),JSON.stringify({indices:[1,4]}));
assert.equal(JSON.stringify(raw.questions.find(q=>q.question_number===28).answer),JSON.stringify({indices:[0,2,3,4]}));
assert.equal(JSON.stringify(raw.questions.find(q=>q.question_number===31).answer),JSON.stringify({indices:[0,1,4]}));
assert.match(raw.questions.find(q=>q.question_number===32).answer.reference,/教育栽培子孫/);
assert.match(raw.questions.find(q=>q.question_number===34).answer.reference,/婚姻/);

assert.equal(staging.review_summary.total,36);
assert.equal(staging.review_summary.expected_question_count,36);
assert.deepEqual(staging.review_summary.missing_question_numbers,[]);
assert.deepEqual(staging.review_summary.exam_errors,[]);
assert.deepEqual(staging.review_summary.by_type,{multiple_choice:7,short_answer:3,single_choice:26});
assert.equal(staging.review_summary.clean,22);
assert.equal(staging.review_summary.needs_review,14);
assert.equal(staging.review_summary.group_needs_review,7);
assert.equal(staging.review_summary.error_count,0);
assert.equal(staging.review_summary.warning_count,14);
assert.equal(staging.review_summary.group_error_count,0);
assert.equal(staging.review_summary.group_warning_count,7);
assert.deepEqual(staging.review_summary.by_reason,{official_answer_objection_resolved:14});
assert.deepEqual(staging.review_summary.by_group_reason,{external_context_required:7,rights_review_required:7});
assert.equal(staging.group_exception_queue.length,7);
assert.equal(staging.exception_queue.length,14);
assert.equal(staging.exception_queue.every(x=>x.reasons.length===1&&x.reasons[0]==='official_answer_objection_resolved'),true);
assert.equal(staging.questions.filter(q=>q.objection_url).length,14);
assert.equal(staging.questions.every(q=>q.classification_status==='needs_review'&&q.pipeline_stage==='staging'&&!q.published),true);
assert.equal(staging.review_summary.ready_for_human_review,true);
assert.equal(staging.review_summary.ready_for_publish,false);

const context={window:{}};vm.createContext(context);
for(const file of ['gsat-111-unified-bank.js','gsat-112-unified-bank.js','gsat-113-unified-bank.js','gsat-114-unified-bank.js','gsat-115-unified-bank.js','gsat-115-chinese-unified-bank.js','unified-question-bank.js'])vm.runInContext(fs.readFileSync(new URL(`../${file}`,import.meta.url),'utf8'),context,{filename:file});
const runtime=context.window.UnifiedQuestionBank;
assert.equal(runtime.filter({subject:'chinese',academic_year:115}).length,36);
assert.equal(runtime.questions.filter(q=>q.subject==='math').length,100);
assert.equal(runtime.questions.length,136);
assert.equal(runtime.questions.filter(q=>q.subject==='chinese').every(q=>q.variant==='國綜'&&q.explanation_status==='draft_review_required'),true);
assert.match(runtime.filter({subject:'chinese'})[0].explanation,/考什麼：.+破題關鍵：.+完整步驟：.+常見錯誤：/);
const linked=runtime.group('ceec-115-chinese-g06-08');
assert.equal(linked.context_delivery,'official_pdf_reference');
assert.match(linked.source_url,/ceec\.edu\.tw/);
console.log('GSAT 115 Chinese Golden Sample staging, answers, groups, and group exception queue PASS');
