import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import fs from 'node:fs';
const require=createRequire(import.meta.url);
const sources=require('../school-exam-sources.js');
const drafts=require('../data/staging/cksh-114-1-1-g1-chinese-explanations.js');
const intake=require('../data/staging/cksh-114-1-1-g1-chinese-intake.cjs');
const paper=sources.forSchool('成功高中')[0];
assert.equal(sources.papers.length,1);
assert.equal(paper.expected_question_count,34);
assert.equal(paper.printed_answers.length,34);
assert.equal(Object.keys(drafts).length,34,'one draft explanation per original question number');
assert.equal(intake.questions.length,34);
assert.equal(new Set(intake.questions.map(q=>q.id)).size,34);
assert.deepEqual(intake.questions.map(q=>q.question_number),Array.from({length:34},(_,i)=>i+1));
assert.deepEqual(intake.questions.map(q=>q.printed_answer),paper.printed_answers);
assert.equal(intake.groups.length,7);
assert.equal(intake.questions.filter(q=>q.questionType==='single_choice').length,22);
assert.equal(intake.questions.filter(q=>q.questionType==='multiple_choice').length,10);
assert.equal(intake.questions.filter(q=>q.questionType==='short_answer').length,2);
assert.equal(intake.ready_for_publish,false);
assert.equal(intake.questions.filter(q=>q.published).length,0);
assert.equal(intake.questions[22].answer_match,false);
assert(intake.questions[22].review_reasons.includes('printed_answer_semantic_conflict'));
for(const n of [5,25,29])assert(intake.questions[n-1].review_reasons.includes('explanation_inference_needs_review'));
assert(intake.questions.every(q=>q.explanation_draft_present&&q.classification_status==='needs_review'));
assert(intake.questions.every(q=>q.review_reasons.includes('question_stem_and_options_not_verified')));
for(let n=1;n<=34;n++){
 const e=drafts[n];assert(e&&e.concept&&e.key_insight&&e.reasoning&&e.common_errors,`Q${n} explanation layers`);
 assert.equal(e.explanation_status,'draft_review_required');
 assert.equal(e.option_analysis.length,n===32||n===33?0:n>=21&&n<=30?5:4,`Q${n} option analysis`);
}
assert.match(drafts[23].reasoning,/不能作正式答案或自動計分/);
assert.equal(paper.printed_answers[22],'ABD');
assert.equal(paper.answer_review[0].question_number,23);
assert.equal(paper.answer_review[0].status,'needs_review');
assert.equal(paper.status,'needs_review');
assert.equal(paper.published,false);
assert.deepEqual(sources.published(),[]);
assert.equal(sources.forSchool('建國中學').length,0);
assert.match(paper.source_url,/^https:\/\/www\.cksh\.tp\.edu\.tw\/.+\.pdf$/);
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
assert(html.indexOf('school-exam-sources.js?')<html.indexOf('app.js?'));
const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
assert(app.includes('SchoolExamSources?.forSchool(n)'));
assert(app.includes('另有 ${papers.length} 份校方試卷待複核，不計入可作答題數'));
const unified=fs.readFileSync(new URL('../unified-question-bank.js',import.meta.url),'utf8');
assert(!unified.includes(paper.id),'staging paper must not enter the playable bank');
console.log('School paper intake PASS: 34 answers transcribed, Q23 blocked, no playable questions');
