const assert=require('node:assert/strict');
module.exports=async function({browser,url}){
 const page=await browser.newPage(),errors=[],requests=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
 await page.route('https://**',r=>r.abort());
 await page.addInitScript(()=>{window.navigationMarker='same-document';localStorage.setItem('v42wrong','[1]');localStorage.setItem('wrong','[{"id":1,"q":"legacy"}]');localStorage.setItem('studyQueue','[{"id":1,"question":"legacy","options":["a","b"],"answer":0}]');localStorage.setItem('v42hist','{"實數":{"ok":2,"total":3}}');});
 await page.goto(url);await page.waitForTimeout(200);
 assert.ok(!requests.some(r=>r.includes('chinese-data.js')),'math startup must not load Chinese question bank');
 const old=await page.evaluate(()=>[localStorage.wrong,localStorage.v42wrong,localStorage.v42hist]);
 await page.selectOption('#subject','chinese');await page.waitForFunction(()=>document.getElementById('bankTotalN').textContent==='150');
 assert.equal(await page.locator('#curriculumTrackField').isVisible(),false);assert.equal(await page.locator('#subjectEntrances').isVisible(),true);
 assert.equal(await page.evaluate(()=>window.navigationMarker),'same-document');
 for(const grade of ['1','2']){
  await page.selectOption('#grade',grade);
  await page.locator('#subjectEntrances [data-subject-mode="exam"][data-open="practice"]').click();assert.equal(await page.locator('#quiz .qcard').count(),20);
  assert.ok(await page.evaluate(()=>[...document.querySelectorAll('#quiz [data-q]')].every(e=>Number(e.dataset.q)<-5000000)));
  await page.locator('#quiz .opt').first().click();await page.locator('#finishBtn').click();
  await page.locator('#quiz [data-dontknow-q]').first().click();await page.locator('#practice [data-home]').click();
  await page.locator('#subjectEntrances [data-open="mock"]').click();await page.locator('#startMock').click();assert.equal(await page.locator('#mockQuiz .qcard').count(),20);
  await page.locator('#mockQuiz .opt').first().click();await page.locator('#submitMock').click();assert.match(await page.locator('#mockResult').innerText(),/已作答 1 題/);await page.locator('#mock [data-home]').click();
 }
 assert.deepEqual(await page.evaluate(()=>[localStorage.wrong,localStorage.v42wrong,localStorage.v42hist]),old,'Chinese attempts must leave old math data intact');
 await page.locator('#subjectEntrances [data-open="classicalPanel"]').click();
 assert.equal(await page.locator('[data-text-id]').count(),15);
 await page.locator('[data-text-action="all"]').click();assert.equal(await page.locator('[data-text-id]:checked').count(),15);
 await page.locator('[data-text-action="clear"]').click();assert.equal(await page.locator('[data-text-id]:checked').count(),0);
 await page.locator('[data-text-id="tao-taohuayuan"]').check();assert.match(await page.locator('#singleTextDetails').innerText(),/單篇精讀/);
 await page.evaluate(()=>document.querySelectorAll('[data-skill-id]').forEach(e=>{e.checked=e.dataset.skillId==='meaning';e.dispatchEvent(new Event('change',{bubbles:true}));}));
 await page.locator('#startClassical').click();assert.equal(await page.locator('#quiz .qcard').count(),1);assert.equal(await page.locator('#quiz .readingPassage').count(),1);
 const answer=page.locator('#quiz .opt').filter({hasText:/交錯相通/});await answer.click();assert.ok(await answer.evaluate(e=>e.classList.contains('correct')));await page.locator('#finishBtn').click();await page.locator('#quiz [data-dontknow-q]').first().click();await page.locator('#practice [data-home]').click();
 await page.locator('#subjectEntrances [data-open="classicalPanel"]').click();assert.match(await page.locator('#singleTextDetails').innerText(),/重要字義：1 題；100%/);
 await page.selectOption('#classicalSource','ceec');await page.locator('#startClassical').click();assert.equal(await page.locator('#quiz .qcard').count(),0);await page.locator('#practice [data-home]').click();
 await page.locator('#subjectEntrances [data-open="classicalPanel"]').click();await page.selectOption('#classicalGroup','extended15');assert.equal(await page.locator('[data-text-id]').count(),15);assert.equal(await page.locator('[data-text-id]:checked').count(),0);
 await page.locator('[data-text-action="all"]').click();await page.selectOption('#classicalSource','real-first');
 await page.locator('#startClassical').click();assert.ok(await page.locator('#quiz .qcard').count()>0);await page.locator('#practice [data-home]').click();
 await page.locator('#subjectEntrances [data-open="classicalPanel"]').click();await page.selectOption('#classicalGroup','all');assert.equal(await page.locator('[data-text-id]').count(),30);
 await page.locator('[data-text-action="weak"]').click();await page.locator('#classicalWeakOnly').check();
 assert.ok(await page.locator('[data-text-id]:checked').count()>0);await page.locator('#classicalPanel [data-home]').click();
 await page.locator('#subjectEntrances [data-subject-mode="reading"]').click();assert.ok(await page.locator('#quiz .readingPassage').count()>0);
 const passages=await page.locator('#quiz .readingPassage').allTextContents();assert.equal(new Set(passages).size,passages.length);await page.locator('#practice [data-home]').click();
 await page.locator('#subjectEntrances [data-open="wrong"]').click();assert.equal(await page.inputValue('#wrongSubject'),'chinese');assert.ok(await page.locator('#wrongList .qcard').count()>0);
 assert.ok((await page.locator('#wrongList .tag').allTextContents()).every(t=>t==='國文'));
 await page.selectOption('#wrongSubject','all');assert.match(await page.locator('#wrongList').innerText(),/數學/);await page.locator('#wrong [data-home]').click();
 await page.locator('#subjectEntrances [data-open="learningAnalytics"]').click();assert.match(await page.locator('#subjectAnalytics').innerText(),/國文學習數據/);await page.locator('#learningAnalytics [data-home]').click();
 await page.locator('#home [data-open="coverage"]').filter({visible:true}).first().click();
 await page.waitForFunction(()=>document.getElementById('coverageMatrix').textContent.includes('未收集'));
 assert.equal(await page.locator('#textCoverage .card').count(),30);
 assert.equal(await page.locator('#coverageMatrix tbody td.coverageNo').count(),144);
 await page.locator('#coverage [data-home]').click();
 await page.setViewportSize({width:390,height:844});await page.locator('#subjectEntrances [data-open="classicalPanel"]').click();
 const settingsBox=await page.locator('#settingsBtn').boundingBox();assert.ok(settingsBox.width>=100&&settingsBox.height<=48,'settings button must remain horizontal at 390px');
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('[data-text-action="all"]').click();await page.selectOption('#classicalSource','platform');await page.locator('#classicalPanel [data-home]').click();
 if(process.env.V5_CAPTURE_DIR){
  const fs=require('node:fs'),path=require('node:path');fs.mkdirSync(process.env.V5_CAPTURE_DIR,{recursive:true});
  await page.waitForFunction(()=>!document.getElementById('toast').classList.contains('showToast'));
  await page.screenshot({path:path.join(process.env.V5_CAPTURE_DIR,'v5-home-mobile.png')});
  await page.locator('#subjectEntrances [data-open="classicalPanel"]').click();
  await page.screenshot({path:path.join(process.env.V5_CAPTURE_DIR,'v5-classical-mobile.png')});
  await page.locator('#skillChoices').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(process.env.V5_CAPTURE_DIR,'v5-skills-mobile.png')});
  await page.locator('#classicalPanel [data-home]').click();await page.locator('#subjectEntrances [data-open="historical"]').click();
  await page.locator('#subjectHistoryFilters').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(process.env.V5_CAPTURE_DIR,'v5-history-mobile.png')});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.locator('#historical [data-home]').click();
 }
 await page.selectOption('#subject','math');await page.waitForFunction(()=>document.getElementById('title').textContent.includes('數學'));
 assert.equal(await page.evaluate(()=>window.navigationMarker),'same-document');assert.equal(await page.inputValue('#grade'),'2');assert.equal(await page.locator('#curriculumTrackField').isVisible(),true);
 await page.selectOption('#grade','1');assert.equal(await page.locator('#bankTotalN').innerText(),'250');assert.equal(await page.locator('#wrongN').innerText(),'1');
 assert.equal(requests.filter(r=>r.includes('chinese-data.js')).length,1,'subject data cached after lazy load');
 assert.deepEqual(errors,[]);await page.close();console.log('PASS: V5 browser: Chinese grades 1/2, exam/mock, 15+15 selection, skills/source/weak filters, passage groups, mastery, cross-subject isolation, lazy load, 390px.');
};
